### PR TITLE
Added not-found error message for hostname search

### LINKED ISSUE #48: Search for non-existing hostname results not in correct exception
**Describe the bug**

Look up for a non existing call raises a PHPyPAMException not PHPyPAMEntityNotFoundException.

**To Reproduce**

`pi.get_entity(controller='addresses', controller_path=f"search_hostname/{hostname}/")`

**Expected behavior**

PHPyPAMEntityNotFoundException should be raised instead. 

**Versions:**

phpypam <= 1.0.1

**Additional context**

### PR DESCRIPTION
**Pull request by mattiasa**
The following call raises a PHPyPAMException.

```
pi.get_entity(controller='addresses', controller_path=f"search_hostname/{hostname}/")
```

I would expect the library to raise PHPyPAMEntityNotFoundException instead. This PR fixes this by adding the error returned from phpipam to the expected list.

### CODE REVIEW

**Comment by cmeissner** [comment]
@mattiasa many thanks for submitting this pull request. May I ask you to provide a first test case for that exception. We would be very appreciated if you can do this.

**Comment by mattiasa** [comment]
Sure, I can do that. I looked around among the tests and couldn't find anything that tested the actual server responses but I'll come up with something.

**Comment by cmeissner** [comment]
Yeah unfortunately we don't have tests for all the exceptions yet. But this pr is a good starting point for that.

**Review by cmeissner — APPROVED** [review]
The change isn't complex and it works for me.

**Comment by cmeissner** [comment]
@mattiasa I had some time to implement a first version for testing the `PHPyPAMEntityNotFoundException`. Hope this is okay for you.

**Review by cmeissner — APPROVED** [review]

**Comment by mattiasa** [comment]
Yea, thanks a lot for writing the tests. I didn't even get to a point where I could run the test suite before I had to put it aside for some other things.

**Pull request merged**
